sudo: required

services:
  - docker

before_install:
- docker build --squash -t puteulanus/nal .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push puteulanus/nal
