sudo: required

services:
  - docker

before_install:
- docker build -t puteulanus/nal .

script:
  - docker run -it puteulanus/nal nginx -t | tee log.txt
  - cat log.txt | grep -q 'test is successful'
