sudo: required

services:
  - docker

before_install:
  - pip install docker-squash
  - docker build -t puteulanus/nal:tmp .
  - docker-squash -t puteulanus/nal puteulanus/nal:tmp -f alpine:3.15
  - VER=$(docker run -it puteulanus/nal nginx -v | awk -F '[-)]' '{print $(NF-1)}')
  - docker tag puteulanus/nal puteulanus/nal:$VER

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push puteulanus/nal
  - docker push puteulanus/nal:$VER
