#!/bin/sh

curl -sL https://$DOMAIN/.well-known/jwks.json > /etc/nginx/secret.json
sed -i "s#domain: ''#domain: '$DOMAIN'#" /usr/share/auth0/auth0_login/config.js
sed -i "s#clientID: ''#clientID: '$CLIENT_ID'#" /usr/share/auth0/auth0_login/config.js

nginx -c /etc/nginx/nginx.conf -g 'daemon off;'
