name: Docker build and push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          docker build -t puteulanus/nal .
          VER=$(docker run puteulanus/nal nginx -v | awk -F '[-)]' '{print $(NF-1)}')
          docker tag puteulanus/nal puteulanus/nal:$VER

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push puteulanus/nal
          docker push puteulanus/nal:$VER
